spring.application.name=estoque-api

# O endereço onde o banco está rodando e o nome dele no final
spring.datasource.url=jdbc:postgresql://localhost:5432/estoque_galpao

# O usuário padrão "master" do PostgreSQL
spring.datasource.username=postgres

# AQUI VOCÊ TROCA PELA SENHA QUE CADASTROU NA INSTALAÇÃO
spring.datasource.password=1234

# A mágica do JPA: diz pro Spring criar ou atualizar as tabelas sozinho baseado nas suas classes
spring.jpa.hibernate.ddl-auto=update

# Mostra os comandos no terminal pra gente ver o banco trabalhando por trás dos panos
spring.jpa.show-sql=true

# Obriga o Spring a dar erro se receber dados que não pertencem ao equipamento
spring.jackson.deserialization.fail-on-unknown-properties=true

api.security.token.secret=${JWT_SECRET:minha_senha_super_secreta_de_desenvolvimento_123}